# chrome driver地址
service_location: /Users/wayne/Downloads/work/chromedriver-mac-arm64/chromedriver
# chrome调试地址
debugger_address: 127.0.0.1:9222/devtools/browser/b7a33715-7d1d-42a2-abbc-f3bbd0b7aa36
#debugger_address: 127.0.0.1:9222

driver_type: "chrome"
#driver_type: "firefox"

# 是否包含自定义footer
include_footer: true
# 文章的标题
title: 一键自动化博客发布工具,用过的人都说好(segmentfault篇)
# 文章的内容
content: /Users/wayne/Downloads/blogthings/blogs/blog/projects/003-auto-blog-publish-tool-segmentfault.md
# 文章的摘要
summary: 使用一键自动化博客发布工具blog-auto-publishing-tools把博客发布到segmentfault上。

# 是否自动发布博客，不经过人工review
auto_publish: False

enable:
  csdn: True
  jianshu: True
  juejin: True
  segmentfault: False
  oschina: True
  cnblogs: True
  zhihu: True
  cto51: True
  infoq: True
  toutiao: True
  alicloud: True
  txcloud: True
