# chrome driver地址
service_location: /Users/wayne/Downloads/work/chromedriver-mac-arm64/chromedriver
# chrome调试地址
#debugger_address: 127.0.0.1:9222/devtools/browser/2fa59d8a-7d9e-491d-8e51-8d0ca0c8f9e4
debugger_address: 127.0.0.1:9222

driver_type: "chrome"
#driver_type: "firefox"

# 是否包含自定义footer
include_footer: true
# 文章的标题
title: 一键自动化博客发布工具,chrome和firfox详细配置
# 文章的内容
content: /Users/wayne/Downloads/blogthings/blogs/blog/projects/002-auto-blog-publish-tool-chrome-firfox.md
# 文章的摘要
summary: blog-auto-publishing-tools博客自动发布工具现在已经可以同时支持chrome和firefox了.

# 是否自动发布博客，不经过人工review
auto_publish: False

enable:
  csdn: True
  jianshu: True
  juejin: True
  segmentfault: True
  oschina: True
  cnblogs: True
  zhihu: True
  cto51: True
  infoq: True
  toutiao: True
  alicloud: True
  txcloud: True
