# chrome driver地址
#service_location: /Users/wayne/Downloads/work/chromedriver-mac-arm64/chromedriver
service_location: /home/mao/Downloads/chromedriver-linux64/chromedriver
#service_location: /Users/wayne/Downloads/work/firefoxdriver/geckodriver
# chrome调试地址
debugger_address: 127.0.0.1:9222

# firfox调试地址
#debugger_address: 127.0.0.1:2828

driver_type: "chrome"
#driver_type: "firefox"

# 是否包含自定义footer
include_footer: true
# 要发布的文章目录
content_dir : /home/mao/workspace/medium_scrape/analysis_results

# 文章的标题
title: AI重塑零售：智能体验新纪元
# 文章的内容
content: /home/mao/workspace/medium_scrape/analysis_results/generative-erp-crm-4982dab5a49e_complete_analysis.md
# 文章的摘要
summary: AI技术在零售业中的应用正在深刻改变消费者的购物体验，特别是在个性化推荐、视觉搜索和动态定价方面。个性化推荐通过分析消费者行为数据，提供定制化的产品建议，提升购物精准度；视觉搜索技术让消费者通过图片快速找到商品，增强了购物的直观性和便捷性；动态定价则根据市场需求和竞争情况实时调整价格，帮助零售商最大化利润并保持竞争力。此外，AI驱动的预测分析优化了库存管理和供应链效率，减少了库存积压和缺货现象，降低了成本并提升了客户满意度。这些技术的应用不仅让购物更加智能高效，也为零售商带来了更多商业机会，推动了零售业的全面升级。

# 是否自动发布博客，不经过人工review
auto_publish: True

# 是否等待页面登录
wait_login: True
# 等待login的时间 默认2分钟
wait_login_time : 120

# 发布记录文件路径
published_record_file: /home/mao/workspace/medium_scrape/published_articles.txt

enable:
  csdn: True
  jianshu: False
  juejin: False
  segmentfault: False
  oschina: False
  cnblogs: False
  zhihu: True
  cto51: False
  infoq: False
  toutiao: False
  alicloud: False
  txcloud: False
  mpweixin: False

