# chrome driver地址
service_location: /Users/wayne/Downloads/work/chromedriver-mac-arm64/chromedriver
# chrome调试地址
debugger_address: localhost:9222/devtools/browser/4aab2b8b-112c-48a3-ba38-5ba5f833fb1c

# 是否包含自定义footer
include_footer: true
# 文章的标题
title: Stable Diffusion中的embedding
# 文章的内容
content: /Users/wayne/Downloads/blogthings/blogs/docs/AIGC/stable-diffusion/006-embedding.md
# 文章的摘要
summary: 嵌入，也称为文本反转，是在 Stable Diffusion 中控制图像样式的另一种方法。在这篇文章中，我们将学习什么是嵌入，在哪里可以找到它们，以及如何使用它们。

# 是否自动发布博客，不经过人工review
auto_publish: False

enable:
  csdn: True
  jianshu: True
  juejin: True
  segmentfault: True
  oschina: True
  cnblogs: True
  zhihu: True
  cto51: True
  infoq: True
  toutiao: True
  alicloud: True
  txcloud: True
